### ISSUE TITLE
Release it on crates.io

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/rabe#1]
See https://doc.rust-lang.org/cargo/commands/cargo-publish.html

**Comment by JulianSchuette** [comment]
This is not trivial, unfortunately.

This project depends on `georgbramm/bn` which is a fork of `zcash-hackworks/bn`. The former is not available as a crate, the latter seems to be not maintained anymore (the last PR is open for >2yrs).

Publishing to crates.io requires all dependencies to be available on crate.io as well. So, there are only two options:

1) Create a PR and convince the maintainers of zcash-hackworks to accept and publish it as a version bn:0.4.4

2) Publish georgbramm/bn as a whole new crate, say under the name bn-serde.


(1) would obviously be favorable, but the chances of convincing the zcash authors to accept a major breaking PR in the near future are low.

(2) irreversibly creates a new forked crate and may lead to further confusion

**Comment by georgbramm** [comment]
Releases :
https://crates.io/crates/rabe-bn
and
https://crates.io/crates/rabe

=)
