### ISSUE TITLE
HumanPolicy failed

### ISSUE THREAD

**Issue by wkwai** [Fraunhofer-AISEC/rabe#14]
The following will cause panic:

        let human = String::from("(B and C)");
        let _human_val: PolicyValue = parse(&human, PolicyLanguage::HumanPolicy).expect("unsuccessful parse");

**Comment by PekeDevil** [comment]
According to the [documents](https://docs.rs/rabe/latest/rabe/schemes/ac17/index.html), that policy should be expressed as: `let policy = String::from(r#""A" and "B""#);` Your code lacks de `r#`.

Also, with that code, you would already have the policy properly encoded in `policy`. To use it later:

`let sk: Ac17KpSecretKey = kp_keygen(&msk, &policy, PolicyLanguage::HumanPolicy).unwrap();`

**Comment by wkwai** [comment]
> According to the [documents](https://docs.rs/rabe/latest/rabe/schemes/ac17/index.html), that policy should be expressed as: `let policy = String::from(r#""A" and "B""#);` Your code lacks de `r#`.
> 
> Also, with that code, you would already have the policy properly encoded in `policy`. To use it later:
> 
> `let sk: Ac17KpSecretKey = kp_keygen(&msk, &policy, PolicyLanguage::HumanPolicy).unwrap();`

Thanks, you're absolutely correct
