### ISSUE TITLE
Duplicate attributes not supported in BSW scheme

### ISSUE THREAD

**Issue by wkwai** [Fraunhofer-AISEC/rabe#15]
The following policy with duplicated attribute "B" would caused decryption in BSW scheme to fail:

        let policy = String::from(r#"{"name": "or", "children": [{"name": "and", "children":  [{"name": "A"}, {"name": "B"}]}, {"name": "and", "children":  [{"name": "C"}, {"name": "B"}]}]}"#);

I've tested with the Python implementation by the original BSW authors and duplicated attributes are supported. Their paper also mentioned duplicated attributes are supported.

Please help to resolve this.

**Comment by georgbramm** [comment]
I will have look in the course of this week... sorry for the late response =)

**Comment by georgbramm** [comment]
should be fixed now
