### ISSUE TITLE
Getting "The following required arguments were not provided" when compiling rabe-console

### ISSUE THREAD

**Issue by Keeeeeeeks** [Fraunhofer-AISEC/rabe#16]
Hi all,

I compiled and built the lib based on the readme in the parent directory, but for some reason running `rabe` commands led to a 'zsh: command not found: rabe' error, suggesting something went wrong.

WHen I went to compile rabe-console, everything but the last step worked. Running ```../target/release/rabe``` returned the following error:

```error: The following required arguments were not provided:
    --s <s>

USAGE:
    rabe [OPTIONS] --s <s> [SUBCOMMAND]

For more information try --help```

which is cyclical because `rabe --help` doesn't work either.

How should I troubleshoot this?

**Comment by PekeDevil** [comment]
What is exactly the command you use? If you run `rabe --s AC17CP, what is the output?

**Comment by Keeeeeeeks** [comment]
```$ rabe % rabe --s AC17CP setup
zsh: command not found: rabe

$ rabe % ls
Cargo.lock      LICENSE         benches         src
Cargo.toml      README.md       rabe-console    target

$ rabe % cd rabe-console

$ rabe-console % rabe --s AC17CP setup

zsh: command not found: rabe ```

command isn't found. I tried installing rabe and running the executable mentioned in the rabe-console step, and got the error mentioned in the first comment

**Comment by PekeDevil** [comment]
Okay, I think you may be messing up some commands. There are three options to build rabe-console:

1. From the parent directory using `cargo run -p rabe-console`
2. From the rabe-console directory using `cargo run`
3. Using `cargo build --release`  and then run the executable `./target/release/rabe`

After you have compiled rabe, to use the command line interface, you can run commands **from the directory in which you want to have your project** `rabe --s AC17CP setup` (for example).

I think what is happening to you is that:

1. You're mixing up the compiling commands with the running commands.
2. You're trying to have your project folder inside the rabe directory.

Can you please check the above and tell us if the issue goes away? :)

**Comment by georgbramm** [comment]
If you still need help please contact us again here
