### ISSUE TITLE
Library fails to process policies with more than 60 attributes.

### ISSUE THREAD

**Issue by schanzen** [Fraunhofer-AISEC/rabe#4]
More or less.
You need to create a policy with ~80 attributes to produces the bug and call encrypt/keygen, respectively.
Unclear if this is a parser issue or scheme issue.
Happens with AC17/BSW schemes (all).

**Comment by schanzen** [comment]
```
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic
             at src/libcore/panicking.rs:49
   9: core::option::Option<T>::unwrap
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/macros.rs:12
  10: rabe::schemes::bsw::encrypt
             at /root/.cargo/git/checkouts/rabe-a312a3fe5f1c33cf/951f1c8/src/schemes/bsw/mod.rs:227
...
```

**Comment by schanzen** [comment]
I used the library and not the CLI tools.

**Comment by georgbramm** [comment]
should be fixed now (with commit)
https://github.com/Fraunhofer-AISEC/rabe/commit/3a63de9938e429446c16766690a734f7f6787c6c

**Comment by georgbramm** [comment]
I added a "nested" policies level test.

Regarding nested policies:
There is a upper boundary in serde (RecursionLimitExceeded). 
See here for more details: https://github.com/serde-rs/json/issues/334

We are affected by this boundary too. We could mitigate this by a) waiting for a serde improvement or b) writing our own JSON ser/de

Keeping this open

**Comment by georgbramm** [comment]
ahh  i didnt have the time to read to the end last time...
they integrated disable_recursion_limit(&mut self)
but this has some consequences...
https://docs.rs/serde_json/1.0.41/serde_json/struct.Deserializer.html#method.disable_recursion_limit

**Comment by JulianSchuette** [comment]
Can this issue be closed?

**Comment by oxisto** [comment]
@georgbramm Is this fixed?

**Comment by georgbramm** [comment]
is fixed up to maximum json nested level.
If we want deeper nestings we need a better policy language
