### ISSUE TITLE
 in order to create example, how to calculate time based on number of Attributes?

### ISSUE THREAD

**Issue by karim14** [Fraunhofer-AISEC/rabe#6]
Hi, 
in order to create msk and pk of an AC17 KP-ABE scheme, I used all as you say but it is not working. it says "--scheme: command not found".
where should I use this command? in my rabe path "ubuntu:~/rabe" ?
I think the problem is path, I did what you said in "compile and test" and it is work and I have no problem with it.
also I have another issue, how can I calculate time of run based on number of attributes? where can I change the number?
I hope you help me in this, I used so many ways but none works and I can't change number of attributes.
thanks

**Comment by georgbramm** [comment]
Hi, 
i am sorry the console app had a few bugs. 
There is an updated version now in the folder console.
Just build it (cargo build --release)

Do you need a working example how to setup a scheme and run it?
If you want to measure stuff on the console you can use "time" on linux.
For example: 

`georg@bramm:~/Projekte/rust-abe/rabe/console$ time ./target/release/rabe --scheme BSW setup
successfully wrote to msk.key
successfully wrote to pk.key

real	0m0,041s
user	0m0,035s
sys	0m0,004s
`
It took me 0m0,041s to setup a BSW scheme on my machine.
Hope that helped.
Greetings.
