### ISSUE TITLE
YCT14 KP-ABE scheme is broken

### ISSUE THREAD

**Issue by adelapie** [Fraunhofer-AISEC/rabe#8]
Hello,

The YCT14 scheme was broken in [1] and a 'fixed' version was again broken in  [2].
We have demonstrated how the attack can be implemented in practice in https://www.blackhat.com/eu-21/briefings/schedule/index.html#practical-attacks-against-attribute-based-encryption-25058.

[1] https://ieeexplore.ieee.org/document/8651482
[2] https://ieeexplore.ieee.org/document/9291064

**Comment by georgbramm** [comment]
Very cool presentation ! Thanks for the links ! 
We'll mention it in the code ....
