### ISSUE TITLE
About the AES dependency

### ISSUE THREAD

**Issue by PekeDevil** [Fraunhofer-AISEC/rabe#9]
I've been using this library for part of my Ph.D. research. it has proven very useful so far, but I was wondering about the AES cipher used underneath.

I've seen that rabe calls `aes` from `aes-0.7.0.` This crate only offers _AES_ or _AES-CTR_. Seemed weird to me, and I have checked the newest version of `aes` crate and developers comment how:

> _This crate implements only the low-level block cipher function, and is intended for use for implementing higher-level constructions only. It is NOT intended for direct use in applications._

So now I'm wondering what mode of AES does Rabe use. Or whether at some point in the code you build AES-CBC or AES-GCM.

In case Rabe is using pure AES, since this is not recommended, are you planning on implementing [AEADs](https://github.com/RustCrypto/AEADs)?

BTW thanks for all the hard work 😄

**Comment by georgbramm** [comment]
I just released rabe v0.3.1 which now uses aes-gcm =)
Maybe, in the future we will make the symmetric cipher configureable....

**Comment by PekeDevil** [comment]
Amazing news! I will update my testbed with the newest Rabe version.
